# Generated by Django 4.2.6 on 2023-11-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_category_child_category_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='child',
            field=models.ManyToManyField(blank=True, to='product.category'),
        ),
    ]
