# Generated by Django 4.2.6 on 2023-11-24 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_color_product_producttype_size_productitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='size',
            name='product_type',
        ),
        migrations.AddField(
            model_name='color',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colors', to='product.producttype'),
        ),
        migrations.AddField(
            model_name='size',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sizes', to='product.producttype'),
        ),
    ]
