version: '3'

services:
  postgres:
    container_name: postgres-db-p808
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    env_file: .env
