# Generated by Django 4.2.6 on 2023-11-17 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealing',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 16, 39, 49, 653718, tzinfo=datetime.timezone.utc)),
        ),
    ]
