version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ../nginx.conf:/etc/nginx/nginx.conf
      - ../../static:/app/static
      - ../../media:/app/media
    depends_on:
      - "app"

  app:
    container_name: app
    build: ../..
    restart: "always"
    env_file: .env
    environment:
      - VIRTUAL_HOST=138.68.67.113
      - VIRTUAL_PORT=8000
      - HTTP_PORT=8000
      - STATS_PORT=8001
    volumes:
      - ../..:/code
    ports:
      - "8015:8000"
    links:
      - postgres
    depends_on:
      - "postgres"

  postgres:
    container_name: postgres-db
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    env_file: .env

  redis:
    build:
      context: .
      dockerfile: redis.dockerfile
    image: redis:4.0.11
    restart: "on-failure"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redisdb:/var/lib/redis
    env_file: .env

  celery:
    restart: "always"
    build: ../..
    container_name: celery
    env_file: .env
    command: celery --app=app.celery:app worker -B --loglevel=INFO
    volumes:
      - ../..:/code
    links:
      - redis
      - postgres
    depends_on:
      - "redis"
      - "postgres"

networks:
  default:
    external:
      name: nginx-proxy
